version: 2

models:
  - name: customer_lifetime_value
    description: >
      Comprehensive customer lifetime value analysis combining order history,
      revenue metrics, and customer segmentation. Used for identifying high-value
      customers and understanding customer behavior patterns.
    config:
      tags: ['analytics', 'customers', 'metrics']
    columns:
      - name: customer_id
        description: "Natural customer identifier"
        tests:
          - unique
          - not_null

      - name: customer_key
        description: "Foreign key to current customer dimension record"
        tests:
          - not_null
          - relationships:
              to: ref('dim_customers')
              field: customer_key

      - name: email
        description: "Customer email address"
        tests:
          - not_null

      - name: full_name
        description: "Customer full name"
        tests:
          - not_null

      - name: customer_segment
        description: "Current customer segment"
        tests:
          - not_null

      - name: total_orders
        description: "Total number of orders placed by customer"
        tests:
          - not_null

      - name: total_revenue
        description: "Total revenue generated by customer"
        tests:
          - not_null

      - name: avg_order_value
        description: "Average value per order"
        tests:
          - not_null

      - name: first_order_date
        description: "Date of customer's first order"
        tests:
          - not_null

      - name: last_order_date
        description: "Date of customer's most recent order"
        tests:
          - not_null

      - name: customer_lifetime_days
        description: "Number of days between first and last order"
        tests:
          - not_null

      - name: estimated_monthly_revenue
        description: "Estimated average monthly revenue from customer"
        tests:
          - not_null

      - name: value_segment
        description: "Customer value classification (VIP/High Value/Medium Value/Low Value/At Risk)"
        tests:
          - not_null
          - accepted_values:
              values: ['VIP', 'High Value', 'Medium Value', 'Low Value', 'At Risk']

      - name: recency_segment
        description: "Customer recency classification (Active/At Risk/Churning/Churned)"
        tests:
          - not_null
          - accepted_values:
              values: ['Active', 'At Risk', 'Churning', 'Churned']

      - name: frequency_segment
        description: "Customer purchase frequency classification"
        tests:
          - not_null
          - accepted_values:
              values: ['One-Time', 'Occasional', 'Regular', 'Loyal']
