# ==============================================================================
# Modern E-Commerce Analytics Platform - dbt Project Configuration
# ==============================================================================
# This file configures the dbt project for transforming raw e-commerce data
# into analytics-ready dimensional models for business intelligence.
# ==============================================================================

# Project identification
name: 'ecommerce_analytics'
version: '1.0.0'
config-version: 2

# Profile configuration (references ~/.dbt/profiles.yml)
profile: 'ecommerce_analytics'

# Project paths
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

# Documentation paths
docs-paths: ["docs"]

# Asset paths (for images, etc.)
asset-paths: ["assets"]

# Target directory (cleaned by `dbt clean`)
target-path: "target"

# Directories to be removed by `dbt clean`
clean-targets:
  - "target"
  - "dbt_packages"
  - "logs"

# Require dbt version compatibility
require-dbt-version: [">=1.6.0", "<2.0.0"]

# ==============================================================================
# Model Configurations
# ==============================================================================
# Configure how models are materialized and documented
# Materialization strategies:
#   - view: Lightweight, always fresh (staging models)
#   - table: Better performance for frequently queried (marts)
#   - incremental: Efficient updates for large datasets
# ==============================================================================

models:
  ecommerce_analytics:
    
    # =========================================================================
    # STAGING LAYER - Raw data cleaning and standardization
    # =========================================================================
    # Purpose: Light transformations, type casting, column renaming
    # Materialization: Views (low cost, always fresh)
    # Naming: stg_<source>_<entity>
    # =========================================================================
    staging:
      +materialized: view
      +schema: staging
      +docs:
        node_color: "#8BC34A"  # Light green in dbt docs
      
      # Orders staging models
      orders:
        +tags: ["staging", "orders", "daily"]
      
      # Products staging models  
      products:
        +tags: ["staging", "products", "daily"]
      
      # Events staging models
      events:
        +tags: ["staging", "events", "hourly"]
    
    # =========================================================================
    # INTERMEDIATE LAYER - Business logic transformations
    # =========================================================================
    # Purpose: Complex joins, aggregations, deduplication
    # Materialization: Views (unless performance requires tables)
    # Naming: int_<domain>_<description>
    # =========================================================================
    intermediate:
      +materialized: view
      +schema: intermediate
      +docs:
        node_color: "#FF9800"  # Orange in dbt docs
      +tags: ["intermediate"]
    
    # =========================================================================
    # MARTS LAYER - Analytics-ready dimensional models
    # =========================================================================
    # Purpose: Final models for BI tools and reporting
    # Materialization: Tables (optimized for query performance)
    # =========================================================================
    marts:
      +materialized: table
      +docs:
        node_color: "#2196F3"  # Blue in dbt docs
      
      # Core fact tables
      core:
        +schema: marts_core
        +tags: ["marts", "fact", "core"]
        
        # Fact tables use incremental materialization for efficiency
        fact_orders:
          +materialized: incremental
          +unique_key: order_item_key
          +on_schema_change: "fail"
      
      # Dimension tables
      dimensions:
        +schema: marts_dimensions
        +tags: ["marts", "dimension"]
        
        # Slowly Changing Dimensions (Type 2)
        dim_customers:
          +materialized: table
          +tags: ["scd_type_2"]
        
        dim_products:
          +materialized: table
        
        dim_date:
          +materialized: table
          +tags: ["date_dimension"]

# ==============================================================================
# Seeds Configuration
# ==============================================================================
# Static reference data loaded from CSV files
# ==============================================================================
seeds:
  ecommerce_analytics:
    +schema: seeds
    +docs:
      node_color: "#9C27B0"  # Purple in dbt docs

# ==============================================================================
# Snapshots Configuration
# ==============================================================================
# Historical tracking of dimension changes (SCD Type 2)
# ==============================================================================
snapshots:
  ecommerce_analytics:
    +target_schema: snapshots
    +unique_key: id
    +strategy: timestamp
    +updated_at: updated_at

# ==============================================================================
# Data Quality Tests
# ==============================================================================
# Configure test severity levels
# ==============================================================================
tests:
  ecommerce_analytics:
    +severity: error  # Default: tests fail builds
    
    # Staging tests can be warnings (data quality issues logged but not failing)
    staging:
      +severity: warn
    
    # Marts tests should fail (critical for BI accuracy)
    marts:
      +severity: error

# ==============================================================================
# Documentation Settings
# ==============================================================================
vars:
  # Project-level variables
  project_start_date: '2023-01-01'
  project_timezone: 'UTC'
  
  # Data quality thresholds
  max_null_percentage: 0.05  # 5% nulls allowed
  min_row_count: 1000
  
  # Business logic constants
  discount_threshold: 0.20  # 20% discount flag
  high_value_order: 100.00  # $100+ orders

# ==============================================================================
# Performance Optimization
# ==============================================================================
# Query execution settings
on-run-start:
  - "{{ log('Starting dbt run for E-Commerce Analytics Platform', info=True) }}"

on-run-end:
  - "{{ log('Completed dbt run successfully', info=True) }}"

# ==============================================================================
# Dispatch Configuration (for package compatibility)
# ==============================================================================
dispatch:
  - macro_namespace: dbt_utils
    search_order: ['ecommerce_analytics', 'dbt_utils']
