version: 2

models:
  # ==========================================================================
  # FACT TABLE: fact_orders (ENHANCED WITH dbt_expectations)
  # ==========================================================================
  - name: fact_orders
    description: >
      Transaction-level fact table capturing order line items.
      Incrementally loaded based on order_timestamp.
      Contains measures for revenue analysis and foreign keys to all dimensions.
      
      Enhanced with comprehensive dbt tests including:
      - Built-in tests (unique, not_null, relationships)
      - dbt_expectations tests (ranges, expressions, patterns)
      - Custom business logic tests
    config:
      tags: ['fact', 'core', 'orders', 'incremental', 'tested']
    
    # ========================================================================
    # MODEL-LEVEL TESTS (Applied to entire table)
    # ========================================================================
    tests:
      # Test 1: Line total calculation correctness
      - dbt_expectations.expression_is_true:
          expression: "line_total = (quantity * unit_price - coalesce(discount_amount, 0))"
          config:
            severity: error
            error_if: ">10"  # Allow max 10 rounding errors
            warn_if: ">0"    # Warn if any errors exist
          meta:
            description: "Validates revenue calculation accuracy"
            business_rule: "line_total must equal qty * price - discount"
      
      # Test 2: Discount cannot exceed gross amount
      - dbt_expectations.expression_is_true:
          expression: "discount_amount <= (quantity * unit_price)"
          config:
            severity: error
          meta:
            description: "Prevents negative revenue from excessive discounts"
            business_rule: "Discount cannot exceed gross order value"
      
      # Test 3: Row count within expected range
      - dbt_expectations.expect_table_row_count_to_be_between:
          min_value: 0
          max_value: 100000000  # 100 million max
          config:
            severity: warn
          meta:
            description: "Ensures fact table has reasonable data volume"
    
    # ========================================================================
    # COLUMN-LEVEL TESTS
    # ========================================================================
    columns:
      # ======================================================================
      # PRIMARY KEY
      # ======================================================================
      - name: order_item_key
        description: "Surrogate key combining order_id and order_item_id"
        tests:
          - unique:
              config:
                severity: error
          - not_null:
              config:
                severity: error
      
      # ======================================================================
      # FOREIGN KEYS
      # ======================================================================
      - name: customer_key
        description: >
          Foreign key to dim_customers.
          Uses custom test (tests/relationships_fact_orders_current_customers.sql) 
          to validate references to current customers only (is_current = true).
        tests:
          - not_null:
              config:
                severity: error
          # Note: Custom relationship test used instead of built-in test
          # See: tests/relationships_fact_orders_current_customers.sql
          # Validates that customer_key references current customers in dim_customers
      
      - name: product_key
        description: "Foreign key to dim_products"
        tests:
          - not_null:
              config:
                severity: error
          - relationships:
              to: ref('dim_products')
              field: product_key
              config:
                severity: error
      
      - name: date_key
        description: "Foreign key to dim_date"
        tests:
          - not_null:
              config:
                severity: error
          - relationships:
              to: ref('dim_date')
              field: date_key
              config:
                severity: error
      
      # ======================================================================
      # DEGENERATE DIMENSIONS
      # ======================================================================
      - name: order_id
        description: "Degenerate dimension - order identifier"
        tests:
          - not_null:
              config:
                severity: error
      
      - name: order_item_id
        description: "Degenerate dimension - order line item identifier"
        tests:
          - not_null:
              config:
                severity: error
      
      # ======================================================================
      # DATE/TIME FIELDS
      # ======================================================================
      - name: order_date
        description: "Date when order was placed"
        tests:
          - not_null:
              config:
                severity: error
          # Ensure order dates are not in the future
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: "'2023-01-01'"
              max_value: "current_date"
              strictly: false
              config:
                severity: error
              meta:
                description: "Orders cannot be in the future"
      
      - name: order_timestamp
        description: "Timestamp when order was placed"
        tests:
          - not_null:
              config:
                severity: error
      
      # ======================================================================
      # MEASURES - NUMERIC FIELDS
      # ======================================================================
      - name: quantity
        description: "Number of items ordered"
        tests:
          - not_null:
              config:
                severity: error
          # Quantity must be positive and reasonable
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 1
              max_value: 100
              strictly: false
              config:
                severity: error
              meta:
                description: "Order quantity between 1-100 items"
                business_rule: "Prevents data entry errors and fraud"
      
      - name: unit_price
        description: "Price per unit"
        tests:
          - not_null:
              config:
                severity: error
          # Unit price must be positive
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0.01
              max_value: 10000.00
              strictly: false
              config:
                severity: error
              meta:
                description: "Unit price between $0.01 and $10,000"
                business_rule: "Reasonable product pricing range"
      
      - name: discount_amount
        description: "Discount applied to this line item"
        tests:
          # Discount must be non-negative
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0
              max_value: 1000.00  # Max $1000 discount per line
              strictly: false
              config:
                severity: error
              meta:
                description: "Discount between $0 and $1,000"
      
      - name: gross_amount
        description: "Gross line amount before discount (quantity × unit_price)"
        tests:
          - not_null:
              config:
                severity: error
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0
              strictly: false
              config:
                severity: error
      
      - name: line_total
        description: "Net line amount after discount"
        tests:
          - not_null:
              config:
                severity: error
          # Line total must be non-negative
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0
              strictly: false
              config:
                severity: error
              meta:
                description: "Line total must be positive"
                business_rule: "No negative revenue"
      
      - name: net_revenue
        description: "Net revenue for this line item (same as line_total)"
        tests:
          # Net revenue must match line_total
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0
              strictly: false
              config:
                severity: error
      
      # ======================================================================
      # CATEGORICAL FIELDS
      # ======================================================================
      - name: order_status
        description: "Current status of the order"
        tests:
          - not_null:
              config:
                severity: error
          - accepted_values:
              values: ['pending', 'processing', 'shipped', 'delivered', 'cancelled', 'returned', 'completed']
              config:
                severity: error
              meta:
                description: "Order status must be in predefined set"
      
      - name: payment_method
        description: "Payment method used for this order"
        tests:
          - not_null:
              config:
                severity: error
          - accepted_values:
              values: ['credit_card', 'debit_card', 'paypal', 'bank_transfer', 'cash', 'google_pay', 'apple_pay']
              config:
                severity: error
              meta:
                description: "Only supported payment methods allowed"
      
      # ======================================================================
      # DERIVED FIELDS
      # ======================================================================
      - name: has_discount
        description: "Boolean flag indicating if discount was applied"
        tests:
          - not_null:
              config:
                severity: error
          - accepted_values:
              values: [true, false]
              config:
                severity: error
      
      - name: discount_percentage
        description: "Discount as percentage of gross amount"
        tests:
          # Discount percentage between 0-100%
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0
              max_value: 100
              strictly: false
              config:
                severity: warn  # Warn, don't fail
              meta:
                description: "Discount percentage between 0-100%"
      
      - name: order_hour
        description: "Hour of day when order was placed (0-23)"
        tests:
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0
              max_value: 23
              strictly: false
              config:
                severity: error
      
      - name: order_day_of_week
        description: "Day of week (0=Sunday, 6=Saturday)"
        tests:
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0
              max_value: 6
              strictly: false
              config:
                severity: error
